Features
qwibbler/Capstone-Portal pull request #1
Opened 2021-11-15 23:16 UTC by qwibbler

Capstone project for code review.

2021-11-15 23:47 UTC, qwibbler commented
Day 1, finished!

- [ ] Home Page (html, css) all finished except background incomplete.
- [ ] About Page (html, css) all finished.
- [ ] Nav Bar (html, css) all finished
- [ ] Nav Bar hamburger (js) open close all finished except testing close on link and add close on touch outside.
- [ ] Readme initialized.

2021-11-16 23:25 UTC, qwibbler commented
End Day 2

- [ ] Add background pictures.
- [ ] Add scrollspy.
- [ ] Add features page, html, css, js.

Todo:
- [ ] Add footer.
- [ ] Add page by page screenshot.
- [ ] Record video.

2021-11-17 22:46 UTC, rotimiazeez requested changes
# Hi @qwibbler 👋, 

### Good job so far!👏👏
![](https://media.giphy.com/media/12XDYvMJNcmLgQ/giphy.gif)

### SUMMARY❤
- Good README file👏
- No linter error ✔
- Good PR description👍
- Friendly UI✌😎

### There are some issues that you still need to work on to go to the next project but you are almost there!💯

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-17 22:46 UTC, rotimiazeez commented on index.html
> +      <p>
- [x] Please note that the project contains the `Home` page and the `About` page👍 and they are separated with the possibility to navigate between the pages, there's a link from the `Home` page to the `About` page and the opposite too👌😉.  Also, both pages contain the same navbar and footer😎✔.

2021-11-17 22:46 UTC, rotimiazeez commented on index.html
> +    <section class="home" id="homepage">
- [x] Kindly note that your home page should contain a middle section with a column that includes a section header, a divider, five individual articles, each with an image, title, and description, and a line of text at the bottom👀, same as the given [design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)😊.
- Something like this👇:
![screenshot (16)](https://user-images.githubusercontent.com/44624138/142288689-d36e8cbc-8b97-4299-bdde-d149aca17bf4.png)

2021-11-17 22:46 UTC, rotimiazeez commented on index.html
> +    <section class="home" id="homepage">
Kindly know that on mobile the middle section article list is organized in a vertical column😋 and on desktop, the article list is organized in a horizontal row.
- for example
![screenshot (17)](https://user-images.githubusercontent.com/44624138/142290411-a3081f4f-90e9-4779-9720-6c9d09e0c189.png) ![screenshot (16)](https://user-images.githubusercontent.com/44624138/142291277-490cbfe8-cdcf-470f-96d0-dc31914d9afd.png)

2021-11-17 22:46 UTC, rotimiazeez commented on index.html
> +    <section class="about" id="aboutpage">
- [ ] Please make sure the about page contains a middle section with a centered column that includes a section header, a divider, a paragraph of text, and an image or large logo👌 and a bottom section with a centred column that includes a section header, a divider, a line of text, and two images with text centred over them😉.
- design example
![screenshot (19)](https://user-images.githubusercontent.com/44624138/142292239-3fa3ba6d-358c-482b-b8d5-0fe88f0e4fb8.png)

2021-11-17 22:46 UTC, rotimiazeez commented on index.html
> +    <section class="about" id="aboutpage">
Kindly note that on mobile the bottom section images are organized in a vertical column✔ and on desktop, the bottom section images are organized in a horizontal row🙄. 
- example
![screenshot (20)](https://user-images.githubusercontent.com/44624138/142292750-1558f9bc-535c-49e7-bf64-70bb83a6f434.png) ![screenshot (21)](https://user-images.githubusercontent.com/44624138/142292773-2eb2db2d-6255-475e-ab1b-92f35d9df931.png)

2021-11-18 18:46 UTC, GzimAsani approved these changes
# STATUS: APPROVED :100:         
## Thank you for implementing all the project requirements, you've done a great job :trophy: There is nothing else to say other than... it's time to merge it :champagne:  :tada: Congratulations

Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Since it wasn't asked by the previous review I will mark this as optional but it is highly recommended since it was part of the given design. Please add this part of the footer as well:
![Screenshot from 2021-11-18 19-45-44](https://user-images.githubusercontent.com/62705947/142477594-bbd74fe5-f02c-4c15-8389-6d34a30d70ec.png)


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-18 19:12 UTC, merged